version: '3.7'  # Versions: https://docs.docker.com/compose/compose-file/

services:

    web:
        build:
            context: ../..
            dockerfile: ./docker/dev/Dockerfile
        command:
            python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../../app:/usr/src/app/
        ports:
            - 8003:8000
        env_file:
            - ./env/web.env
        depends_on:
            - db

    db:
        image:
            postgres:12-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - ./env/db.env

volumes:
    postgres:
