# Generated by Django 3.0.5 on 2020-04-30 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_auto_20200430_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_state', models.CharField(max_length=64)),
                ('auth_code', models.CharField(max_length=128)),
                ('access_token', models.CharField(max_length=128, null=True)),
                ('access_token_expire_at', models.DateTimeField(null=True)),
                ('scope', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='client.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
