# Generated by Django 3.0.5 on 2020-04-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created_at',)},
        ),
    ]
