# Generated by Django 3.0.5 on 2020-04-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_auto_20200430_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='redirect_uri',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
