# Generated by Django 3.0.5 on 2020-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_auto_20200430_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='auth_code',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
