# Generated by Django 3.0.5 on 2020-04-30 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0005_auto_20200430_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='auth_code_expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
