# Generated by Django 3.0.5 on 2020-04-30 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0006_token_auth_code_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='accessed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
