# Generated by Django 3.0.5 on 2020-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0007_token_accessed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='accessed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
