# Generated by Django 3.0.5 on 2020-05-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth2', '0008_auto_20200430_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='redirect_uri',
            new_name='redirect_forward_uri',
        ),
        migrations.RemoveField(
            model_name='token',
            name='client_state',
        ),
        migrations.AddField(
            model_name='token',
            name='auth_code_remote',
            field=models.CharField(db_index=True, default='-', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='redirect_return_uri',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
