# Generated by Django 3.0.5 on 2020-05-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0009_auto_20200504_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='auth_token_remote',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='scope_remote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='auth_code_remote',
            field=models.CharField(max_length=256),
        ),
    ]
