# Generated by Django 3.0.5 on 2020-05-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0010_auto_20200505_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='auth_token_remote',
            new_name='access_token_remote',
        ),
    ]
