version: '3.7'  # Versions: https://docs.docker.com/compose/compose-file/

services:
    nginx:
        build: ./nginx
        restart: always
        volumes:
            - static_volume:/home/app/web/static
        ports:
            - 1337:8000
        depends_on:
            - web
    web:
        build:
            context: ../..
            dockerfile: ./docker/prod/Dockerfile
        restart: always
        command: gunicorn --workers=6 --threads=2 main.wsgi:application --bind 0.0.0.0:8000 --capture-output
        volumes:
            - static_volume:/home/app/web/static
        expose:
            - 8000
        env_file:
            - ./env/web.env
        depends_on:
            - db
    db:
        restart: always
        image: postgres:12-alpine
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        env_file:
            - ./env/db.env

volumes:
    postgres_volume:
    static_volume:
