# Generated by Django 3.0.5 on 2020-07-02 07:17

from django.db import migrations


def create_config_for_cache(apps, schema_editor):

    Config = apps.get_model('config', 'Config')

    Config.objects.create(
            name='Сервисийн хариуг cache хийх (цагаар)',
            value='0',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_config_for_cache)
    ]
