# Generated by Django 3.0.5 on 2020-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_redirect_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='redirect_uri',
            field=models.CharField(max_length=500),
        ),
    ]
