# Generated by Django 3.0.5 on 2020-04-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200429_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_key',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
